version: '3.9'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
    depends_on:
      - api

  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - 10000:10000
    volumes:
      - ./API:/app
